// import type { Workflow, WorkflowNode, WorkflowEdge } from '@/lib/types';

// const now = new Date();
// const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000).toISOString();

// function makeNodes(): WorkflowNode[] {
//   return [
//     {
//       id: 'n1',
//       type: 'webhook',
//       label: 'Webhook Trigger',
//       description: 'Receives incoming HTTP requests',
//       position: { x: 250, y: 50 },
//       inputs: [],
//       outputs: [{ id: 'o1', name: 'payload', type: 'object' }],
//       config: { method: 'POST', path: '/api/v1/orders' },
//       metadata: { method: 'POST' },
//     },
//     {
//       id: 'n2',
//       type: 'validation',
//       label: 'Input Validation',
//       description: 'Validates request schema against Zod schema',
//       position: { x: 250, y: 180 },
//       inputs: [{ id: 'i1', name: 'payload', type: 'object' }],
//       outputs: [
//         { id: 'o1', name: 'validated', type: 'object' },
//         { id: 'o2', name: 'error', type: 'object' },
//       ],
//       config: { schema: 'CreateOrderSchema', strict: true },
//       metadata: { schema: 'Order' },
//     },
//     {
//       id: 'n3',
//       type: 'business-logic',
//       label: 'Order Processing',
//       description: 'Applies business rules and calculates totals',
//       position: { x: 250, y: 320 },
//       inputs: [{ id: 'i1', name: 'validated', type: 'object' }],
//       outputs: [{ id: 'o1', name: 'processed', type: 'object' }],
//       config: { rules: ['calculate_tax', 'apply_discounts', 'check_inventory'] },
//       metadata: { entity: 'Order' },
//     },
//     {
//       id: 'n4',
//       type: 'database',
//       label: 'Save Order',
//       description: 'Persists order to database via Prisma',
//       position: { x: 250, y: 460 },
//       inputs: [{ id: 'i1', name: 'processed', type: 'object' }],
//       outputs: [
//         { id: 'o1', name: 'saved', type: 'object' },
//         { id: 'o2', name: 'error', type: 'object' },
//       ],
//       config: { model: 'Order', operation: 'create' },
//       metadata: { entity: 'Order', tool: 'prisma-client' },
//     },
//     {
//       id: 'n5',
//       type: 'response',
//       label: 'Success Response',
//       description: 'Returns 201 with created order',
//       position: { x: 100, y: 600 },
//       inputs: [{ id: 'i1', name: 'data', type: 'object' }],
//       outputs: [],
//       config: { statusCode: 201, format: 'json' },
//       metadata: {},
//     },
//     {
//       id: 'n6',
//       type: 'error',
//       label: 'Error Handler',
//       description: 'Handles validation and DB errors',
//       position: { x: 400, y: 600 },
//       inputs: [{ id: 'i1', name: 'error', type: 'object' }],
//       outputs: [],
//       config: { statusCode: 400, format: 'json', includeStack: false },
//       metadata: {},
//     },
//   ];
// }

// function makeEdges(): WorkflowEdge[] {
//   return [
//     { id: 'e1', source: 'n1', target: 'n2', label: 'trigger' },
//     { id: 'e2', source: 'n2', target: 'n3', sourceHandle: 'o1', label: 'valid' },
//     { id: 'e3', source: 'n2', target: 'n6', sourceHandle: 'o2', label: 'invalid' },
//     { id: 'e4', source: 'n3', target: 'n4', label: 'process' },
//     { id: 'e5', source: 'n4', target: 'n5', sourceHandle: 'o1', label: 'success' },
//     { id: 'e6', source: 'n4', target: 'n6', sourceHandle: 'o2', label: 'db error' },
//   ];
// }

// // export const mockWorkflows: Workflow[] = [
// //   {
// //     id: 'wf_001',
// //     name: 'create-order',
// //     description: 'Creates a new customer order with validation, business logic, and database persistence',
// //     purpose: 'Handle order creation from checkout flows',
// //     status: 'active',
// //     endpointType: 'REST',
// //     httpMethod: 'POST',
// //     endpoint: '/api/v1/orders',
// //     requiresAuth: true,
// //     generationMode: 'auto',
// //     entities: ['Order', 'OrderItem', 'Customer', 'Product'],
// //     nodes: makeNodes(),
// //     edges: makeEdges(),
// //     validations: [
// //       { field: 'customerId', rule: 'required', message: 'Customer ID is required', type: 'required' },
// //       { field: 'items', rule: 'minLength:1', message: 'At least one item required', type: 'required' },
// //       { field: 'totalAmount', rule: 'positive', message: 'Total must be positive', type: 'range' },
// //     ],
// //     permissions: ['customer:read', 'order:create', 'inventory:read'],
// //     toolMappings: [
// //       { toolId: 'tool_001', toolName: 'create-order-tool', workflowId: 'wf_001', triggerCondition: 'always', priority: 1 },
// //     ],
// //     versions: [
// //       { id: 'v1', version: '1.2.0', workflowId: 'wf_001', nodes: makeNodes(), edges: makeEdges(), createdAt: daysAgo(5), createdBy: 'admin', changelog: 'Added tax calculation', isActive: true },
// //       { id: 'v2', version: '1.1.0', workflowId: 'wf_001', nodes: makeNodes(), edges: makeEdges(), createdAt: daysAgo(15), createdBy: 'admin', changelog: 'Initial release', isActive: false },
// //     ],
// //     currentVersion: '1.2.0',
// //     n8nWorkflowId: 'n8n_wf_001',
// //     executionCount: 18432,
// //     successRate: 99.1,
// //     avgLatencyMs: 42,
// //     createdAt: daysAgo(30),
// //     updatedAt: daysAgo(5),
// //     approvedAt: daysAgo(28),
// //     approvedBy: 'admin',
// //     tags: ['orders', 'ecommerce', 'critical'],
// //   },
// //   {
// //     id: 'wf_002',
// //     name: 'get-product-catalog',
// //     description: 'Retrieves paginated product catalog with filtering and search',
// //     purpose: 'Serve product listings for storefront and voice assistant',
// //     status: 'active',
// //     endpointType: 'REST',
// //     httpMethod: 'GET',
// //     endpoint: '/api/v1/products',
// //     requiresAuth: false,
// //     generationMode: 'auto',
// //     entities: ['Product', 'Category', 'Brand', 'Inventory'],
// //     nodes: makeNodes(),
// //     edges: makeEdges(),
// //     validations: [],
// //     permissions: ['product:read'],
// //     toolMappings: [
// //       { toolId: 'tool_002', toolName: 'fetch-product-catalog', workflowId: 'wf_002', triggerCondition: 'always', priority: 1 },
// //     ],
// //     versions: [
// //       { id: 'v1', version: '2.0.0', workflowId: 'wf_002', nodes: makeNodes(), edges: makeEdges(), createdAt: daysAgo(10), createdBy: 'admin', changelog: 'Added brand filtering', isActive: true },
// //     ],
// //     currentVersion: '2.0.0',
// //     n8nWorkflowId: 'n8n_wf_002',
// //     executionCount: 54219,
// //     successRate: 99.8,
// //     avgLatencyMs: 28,
// //     createdAt: daysAgo(60),
// //     updatedAt: daysAgo(10),
// //     approvedAt: daysAgo(58),
// //     approvedBy: 'admin',
// //     tags: ['products', 'catalog', 'public'],
// //   },
// //   {
// //     id: 'wf_003',
// //     name: 'process-refund',
// //     description: 'Processes customer refund requests with approval workflow',
// //     purpose: 'Handle refund logic for customer service',
// //     status: 'pending_review',
// //     endpointType: 'REST',
// //     httpMethod: 'POST',
// //     endpoint: '/api/v1/refunds',
// //     requiresAuth: true,
// //     generationMode: 'auto',
// //     entities: ['Order', 'Refund', 'Customer', 'Payment'],
// //     nodes: makeNodes(),
// //     edges: makeEdges(),
// //     validations: [
// //       { field: 'orderId', rule: 'required', message: 'Order ID is required', type: 'required' },
// //       { field: 'reason', rule: 'required', message: 'Reason is required', type: 'required' },
// //       { field: 'amount', rule: 'positive', message: 'Amount must be positive', type: 'range' },
// //     ],
// //     permissions: ['refund:create', 'order:read', 'payment:write'],
// //     toolMappings: [],
// //     versions: [
// //       { id: 'v1', version: '1.0.0', workflowId: 'wf_003', nodes: makeNodes(), edges: makeEdges(), createdAt: daysAgo(1), createdBy: 'ai-generator', changelog: 'AI generated', isActive: true },
// //     ],
// //     currentVersion: '1.0.0',
// //     executionCount: 0,
// //     successRate: 0,
// //     avgLatencyMs: 0,
// //     createdAt: daysAgo(1),
// //     updatedAt: daysAgo(1),
// //     tags: ['refunds', 'finance', 'ai-generated'],
// //   },
// //   {
// //     id: 'wf_004',
// //     name: 'update-inventory',
// //     description: 'Updates product inventory levels with atomic operations',
// //     purpose: 'Sync inventory after orders, returns, and manual adjustments',
// //     status: 'active',
// //     endpointType: 'REST',
// //     httpMethod: 'PATCH',
// //     endpoint: '/api/v1/inventory/:productId',
// //     requiresAuth: true,
// //     generationMode: 'guided',
// //     entities: ['Product', 'Inventory', 'Warehouse'],
// //     nodes: makeNodes(),
// //     edges: makeEdges(),
// //     validations: [],
// //     permissions: ['inventory:write', 'product:read'],
// //     toolMappings: [
// //       { toolId: 'tool_005', toolName: 'update-inventory-tool', workflowId: 'wf_004', triggerCondition: 'on_order', priority: 2 },
// //     ],
// //     versions: [
// //       { id: 'v1', version: '1.3.1', workflowId: 'wf_004', nodes: makeNodes(), edges: makeEdges(), createdAt: daysAgo(3), createdBy: 'admin', changelog: 'Hotfix: race condition', isActive: true },
// //     ],
// //     currentVersion: '1.3.1',
// //     n8nWorkflowId: 'n8n_wf_004',
// //     executionCount: 21847,
// //     successRate: 97.4,
// //     avgLatencyMs: 55,
// //     createdAt: daysAgo(45),
// //     updatedAt: daysAgo(3),
// //     approvedAt: daysAgo(43),
// //     approvedBy: 'admin',
// //     tags: ['inventory', 'critical'],
// //   },
// //   {
// //     id: 'wf_005',
// //     name: 'send-notification',
// //     description: 'Sends multi-channel notifications (email, SMS, push)',
// //     purpose: 'Customer communication for order events',
// //     status: 'error',
// //     endpointType: 'REST',
// //     httpMethod: 'POST',
// //     endpoint: '/api/v1/notifications',
// //     requiresAuth: true,
// //     generationMode: 'auto',
// //     entities: ['Notification', 'Customer', 'NotificationTemplate'],
// //     nodes: makeNodes(),
// //     edges: makeEdges(),
// //     validations: [],
// //     permissions: ['notification:send'],
// //     toolMappings: [],
// //     versions: [
// //       { id: 'v1', version: '1.1.0', workflowId: 'wf_005', nodes: makeNodes(), edges: makeEdges(), createdAt: daysAgo(20), createdBy: 'admin', changelog: 'Added SMS support', isActive: true },
// //     ],
// //     currentVersion: '1.1.0',
// //     n8nWorkflowId: 'n8n_wf_005',
// //     executionCount: 8921,
// //     successRate: 91.2,
// //     avgLatencyMs: 320,
// //     createdAt: daysAgo(50),
// //     updatedAt: daysAgo(1),
// //     approvedAt: daysAgo(48),
// //     approvedBy: 'admin',
// //     tags: ['notifications', 'communication'],
// //   },
// //   {
// //     id: 'wf_006',
// //     name: 'get-customer-profile',
// //     description: 'Retrieves full customer profile with order history',
// //     purpose: 'Customer data for voice assistant and dashboard',
// //     status: 'active',
// //     endpointType: 'REST',
// //     httpMethod: 'GET',
// //     endpoint: '/api/v1/customers/:customerId',
// //     requiresAuth: true,
// //     generationMode: 'auto',
// //     entities: ['Customer', 'Order', 'Address', 'PaymentMethod'],
// //     nodes: makeNodes(),
// //     edges: makeEdges(),
// //     validations: [],
// //     permissions: ['customer:read'],
// //     toolMappings: [
// //       { toolId: 'tool_003', toolName: 'get-customer-profile', workflowId: 'wf_006', triggerCondition: 'on_query', priority: 1 },
// //     ],
// //     versions: [
// //       { id: 'v1', version: '1.0.2', workflowId: 'wf_006', nodes: makeNodes(), edges: makeEdges(), createdAt: daysAgo(2), createdBy: 'admin', changelog: 'Added payment methods', isActive: true },
// //     ],
// //     currentVersion: '1.0.2',
// //     n8nWorkflowId: 'n8n_wf_006',
// //     executionCount: 31204,
// //     successRate: 99.6,
// //     avgLatencyMs: 34,
// //     createdAt: daysAgo(55),
// //     updatedAt: daysAgo(2),
// //     approvedAt: daysAgo(53),
// //     approvedBy: 'admin',
// //     tags: ['customers', 'profile'],
// //   },
// // ];
